version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build      
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
   
 # deploy:
  #  executor:
  #    name: node/default
   # steps:
    #  - checkout
    #  - node/with-cache:
      #    steps:
     #       - run: |
      #         echo "$DOCKER_PWD" | docker login --username $DOCKER_LOGIN --password-stdin

           # build the application image
         #   - run: docker build --tag tic .

           # deploy the image
          #  - run: docker push $DOCKER_IMAGE

workflows:
    build-test:
      jobs:
        - build
        - test:
            requires:
              - build
       # - deploy:
        #    requires:
         #     - test
           
        
          
