version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
 # Deploy with Surge task
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install surge
      - run: ./node_modules/.bin/surge --project ./ --domain tic-tac-toe.surge.sh         
workflows:
    build-test-and-deploy:
      jobs:
        - build-test
        - deploy:
            requires:
              - build-test
          
