version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install --silent
            - run: npm lint        
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test 
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build and push Docker image
                command: |
                  . 
                  docker build -t ourapp/$IMAGE_NAME:$TAG .
                  echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
                  docker push ourapp/$IMAGE_NAME:$TAG
            - run:
                 name: Deploy app tic tac toe via Docker
                 command: |
                    ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ourapp/$IMAGE_NAME:$TAG"
workflows:
    build-test:
      jobs:
        - build
        - lint
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test     
        
          
