version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build      
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test 
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build and push Docker image
                command: |
                  docker build --tag $IMAGE_NAME:$TAG .
                  echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
                  docker push $IMAGE_NAME:$TAG -p 4680:8080 
            - run:
                 name: Deploy app tic tac toe via Docker
                 command: |
                    ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh $IMAGE_NAME:$TAG"
workflows:
    build-test:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test     
        
          
